name: tg-bot-notifier-server docker image build and push

on:
  push:
    branches:
      - master
env:
  CLOUD_RU_ARTIFACT_REGISTRY_URI: thunder-tech-artifacts.cr.cloud.ru

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

# todo - build and push to Cloud.ru Artifact Registry
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CLOUD_RU_ARTIFACT_REGISTRY_URI }}
          username: ${{ secrets.CLOUD_RU_KEY_ID }}
          password: ${{ secrets.CLOUD_RU_KEY_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.CLOUD_RU_ARTIFACT_REGISTRY_URI }}/tg-bot-notifier-server:latest

# todo - build and push to Dockerhub
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          tags: serburyat/tg-bot-notifier-server:latest

# todo - deploy to VDS
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Trigger deployment on VPS
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.VPS_HOST }}
#          username: ${{ secrets.VPS_USER }}
#          key: ${{ secrets.VPS_SSH_KEY }}
#          port: ${{ secrets.VPS_PORT }}
#          script: |
#            cd /path/to/your/deployment/directory
#            ./deploy.sh
