name: tg-bot-notifier-server docker image build and push

on:
  push:
    branches:
      - github-packages-push
env:
  GITHUB_PACKAGES_REGISTRY_URI: ghcr.io

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

# todo - build and push to GitHub Packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Packages container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_PACKAGES_REGISTRY_URI }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.GITHUB_PACKAGES_REGISTRY_URI }}/tg-bot-notifier-server:latest